config/routes.rb
Rails.application.routes.draw do
  
  get 'oauth/new'
  get 'oauth/create'
  get 'oauth/destroy'

  namespace :admin do
    resources :users
  end  
    
  post "likes/:post_id/create" => "likes#create"
  post "likes/:post_id/destroy" => "likes#destroy"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete "posts/:id/destroy" => "posts#destroy"
  delete "/admin/users/:id/destroy" => "users#destroy"
  root to: 'static_pages#home'
  resources :users
  resources :posts

  get "/terms", to: "rules#terms"
  get "/privacy", to: "rules#privacy"


  
  get 'auth/:provider/callback', to: 'oauth#create'
  get 'auth/failure', to: redirect('/')
  
  get "users/:id/likes" => "users#likes"
  get "users/:id/show_false" => "users#show_false"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :oauth, only: %i(new create destroy)
  resources :home, only: %i(index)
  resources :relationships, only: [:create, :destroy]
  resources :posts do 
    resources :advices, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yokatta!</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>

    <!-- Custom fonts for this template -->
    <script src="https://kit.fontawesome.com/8c4eb20b84.js" crossorigin="anonymous"></script>
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navigation -->  
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <%= link_to "Yokatta!", root_path, class:"navbar-brand" %>
       <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
       <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">

          <% if current_user %>

          <li class="nav-item">
            <%= link_to "投稿を見る", posts_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規投稿", new_post_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "プロフィール", "/users/#{current_user.id}", class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", "/logout", method: :delete, class:"nav-link" %>
          </li>

          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "ユーザー一覧", users_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "管理者登録", new_admin_user_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
              <%= link_to "管理者権限編集", "/admin/users/#{current_user.id}/edit", class:"nav-link" %>
            </li>
          <% end %>

          <% else %>
          
          <li class="nav-item">
            <%= link_to "ホーム", posts_path, class:"nav-link" %>
          </li>            
          <li class="nav-item">
            <%= link_to "ログイン", "/login", class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_path, class:"nav-link" %>
          </li>

          <% end %>


          </ul>
       </div>
     </div>
   </nav>

 
   <!-- flash -->     
   <% if flash[:notice].present? %>
     <div class="alert alert-success">
       <%= flash[:notice] %>
     </div>
   <% end %>

   <% if flash[:danger].present? %>
     <div class="alert alert-false">
       <%= flash[:danger] %>
     </div>
   <% end %>

    <%= yield %>

    <!-- Footer -->
    <footer>
      <div class="container">
        <center>
          <%= link_to "利用規約", "/terms", class:"copyright text-muted" %>
          <%= link_to "プライバシーポリシー", "/privacy", class:"copyright text-muted" %>
        </center>
      </div>
    </footer>
    </body>
</html>